nameOverride: ""

clusterName: local-cluster

adminPassword: ""

clusterSubdomain: ""

collector:
  nonAggregatedNetworks: "172.231.0.0/16"

vmScanning:
  enabled: true

argocd:
  enabled: true
  syncwave: "2"
