apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: deployment-file-activity
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  policyName: 'Deployment File Activity'
  categories:
    - File Activity Monitoring
  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT_EVENT
  exclusions:
    - deployment:
        scope:
          namespace: openshift-.*
  severity: LOW_SEVERITY
  policySections:
    - sectionName: Rule 1
      policyGroups:
        - fieldName: File Path
          booleanOperator: OR
          values:
            - value: /etc/**/*
            - value: /boot/**/*
            - value: /usr/bin/**/*
            - value: /usr/lib/**/*
            - value: /usr/lib64/**/*
            - value: /usr/lib/libexec/**/*
            - value: /usr/sbin/**/*
            - value: /usr/share/**/*
            - value: /usr/include/**/*
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
