---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-registration-secret-generator
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "patch"]
