---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acs-mcp-ols-token
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acs-mcp-ols-token
subjects:
  - kind: ServiceAccount
    name: acs-mcp-ols-token
    namespace: {{ .Values.olsNamespace }}
