{{- if .Values.bookinfo.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway
  namespace: {{ .Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingressgateway-secret-reader
  namespace: {{ .Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: istio-ingressgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: {{ .Values.istio.namespace }}
  labels:
    app: istio-ingressgateway
    istio.io/rev: {{ .Values.istio.revision }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        sidecar.istio.io/inject: "true"
        istio.io/rev: {{ .Values.istio.revision }}
    spec:
      containers:
      - name: istio-proxy
        image: auto # replaced by the istiod mutating webhook at pod create
      serviceAccountName: istio-ingressgateway
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: {{ .Values.istio.namespace }}
  labels:
    app: istio-ingressgateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: LoadBalancer
  selector:
    istio: ingressgateway
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: istio-ingressgateway
  namespace: {{ .Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  to:
    kind: Service
    name: istio-ingressgateway
  port:
    targetPort: http
{{- end }}
