---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: {{ .Values.tempo.namespace }}
  labels:
    app: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.tempo.namespace }}
  labels:
    app: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pv-claim
      initContainers:
      - name: create-buckets
        image: quay.io/jitesoft/alpine:latest
        command: ["sh", "-c", "mkdir -p /storage/{{ .Values.minio.bucketName }}"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      containers:
      - name: minio
        image: {{ .Values.minio.image }}
        args: ["server", "/storage", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.accessKeyId | quote }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.minio.accessKeySecret | quote }}
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: /storage
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.tempo.namespace }}
  labels:
    app: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secretName }}
  namespace: {{ .Values.tempo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  bucket: {{ .Values.minio.bucketName }}
  endpoint: {{ .Values.minio.endpoint }}
  access_key_id: {{ .Values.minio.accessKeyId }}
  access_key_secret: {{ .Values.minio.accessKeySecret }}
