---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enable-vsock
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["hco.kubevirt.io"]
    resources: ["hyperconvergeds"]
    verbs: ["get", "patch"]
