{{- if and .Values.agentic.enabled .Values.llm.apiUrl .Values.llm.model }}
---
apiVersion: agentic.openshift.io/v1alpha1
kind: Agent
metadata:
  name: smart
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubernetes.io/description: Temporarily work around https://redhat.atlassian.net/browse/OLS-3734 by defining a 'smart' Agent.  Other than the name, this is a copy of the 'default' Agent.
spec:
  llmProvider:
    name: openai
  model: {{ .Values.llm.model | quote }}
  timeouts:
    analysisSeconds: 120
    executionSeconds: 120
    verificationSeconds: 120
{{- end }}
