---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ .Values.registry.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configBundleSecret: quay-config-bundle
  components:
    - kind: postgres
      managed: true
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: objectstorage
      managed: false
    - kind: route
      managed: {{ if .Values.clusterSubdomain }}false{{ else }}true{{ end }}
    - kind: tls
      managed: true
    - kind: horizontalpodautoscaler
      managed: false
    - kind: mirror
      managed: false
    - kind: monitoring
      managed: true
