{{- if .Values.clusterSubdomain }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quay
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: quay.{{ .Values.clusterSubdomain }}
  to:
    kind: Service
    name: {{ .Values.registry.name }}-quay
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
