apiVersion: v2
name: rhacs-operator
description: Red Hat Advanced Cluster Security for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: acs-operator
    version: 0.1.0
    repository: file://operator
  - name: acs-instance
    version: 0.1.0
    repository: file://instance
