apiVersion: v1
kind: Secret
metadata:
  name: llm-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  apitoken: {{ .Values.llm.apiKey | quote }}
